#!/usr/bin/env bash
TARGET_NAMESPACE="tekton-asa-code"
secrettype=${1}
repoorguser=${2}
secret=${3}

[[ -z ${3} ]] && {
    echo "tkaac-add-secret secrettype repo/org key=value"
}

[[ -z ${secrettype} ]] && { echo "I need a secrettype: i.e: coverage or docker or whatever string to differentiate the puprose of the secret." ;exit 1;}
[[ -z ${repoorguser} ]] && { echo "I need a repoorguser user i.e: openshift/origin"; exit 1 ;}
[[ -z ${secret} ]] && { echo "I need a secret i.e: token=secret"; exit 1 ;}

orguser=${repoorguser%/*}
repo=${repoorguser#*/}

kubectl -n ${TARGET_NAMESPACE} create secret generic ${orguser}-${repo} --from-literal="${secret}"
kubectl label secret ${orguser}-${repo} tekton/asa-code-repoorgusersitory-owner="${orguser}" tekton/asa-code-repoorgusersitory-name="${repo}"