---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-asa-code-listener-interceptor
spec:
  serviceAccountName: tekton-triggers-github-sa
  triggers:
    - name: github-listener
      interceptors:
        - github:
            eventTypes:
              - pull_request
              - issue_comment
        - cel:
            filter: "body.action in ['created', 'opened', 'synchronize'] && 'installation' in body"
      bindings:
        - ref: tekton-asa-code-bindings
      template:
        name: tekton-asa-code-template
